### ISSUE TITLE
线穿过文字时候，文字有错位

### ISSUE THREAD

**Issue by dotfeng** [weidongjian/androidWheelView#10]

**Comment by chihane** [comment]
#6

**Comment by dotfeng** [comment]
如何实现居中对齐呢？

**Comment by chihane** [comment]
这个 -> [LoopView.java](https://github.com/mlxy/Deobfuscating/blob/master/app/src/main/java/com/weidongjian/meitu/wheelviewdemo/view/LoopView.java)

是我之前同时做的另一个反混淆工程，做了居中处理。

可以参考绘制文字用的画笔的初始化和onDraw方法里面绘制文字部分的代码。

概括来说就是指定画笔的文字对齐为居中，然后绘制原点从左下角改为中间。

# 

另外中间项放大的效果我注释掉了，在78行，需要的话可以自行处理。

**Comment by mr235** [comment]
@dotfeng 改成居中显示了

@mlxy 为啥你可以直接提交代码，而我却不行呢，平时工作中用svn，没用git。

**Comment by chihane** [comment]
@mr235 『直接提交代码』是指什么……？

**Comment by mr235** [comment]
@mlxy 我得pull requests才能合到 weidongjian的主线上啊，看你好像是直接就能提交上去了，你的名字都在他的contributors里，我的好像没有

**Comment by chihane** [comment]
@mr235 [你也在啊……](https://github.com/weidongjian/androidWheelView/graphs/contributors)

是要PR然后被合并才能提交上的，我上面发的是当初我自己克隆的工程

---

另外想要直接提交也是可以的，在repo设置的Collaborators里加上的人貌似就可以直接push了

**Comment by mr235** [comment]
@mlxy 谢谢啦，还玩不好github

**Comment by dotfeng** [comment]
onmeasure 中添加了

 switch(widthMode){
            case MeasureSpec.AT_MOST:
                measuredWidth = maxTextWidth + paddingLeft + paddingRight;
                break;
            case MeasureSpec.EXACTLY:
                measuredWidth = widthSize;
                if(paddingLeft == 0 || paddingRight == 0) {
                    paddingLeft = (measuredWidth - maxTextWidth) / 2;
                    paddingRight = paddingLeft;
                }
                break;
            case MeasureSpec.UNSPECIFIED:
                measuredWidth = maxTextWidth + paddingLeft + paddingRight;
            break;
        }

另

public final void setInitPosition(int initPosition) {
        this.initPosition = initPosition;
        totalScrollY = 0;//popup场景
    }

**Comment by weidongjian** [comment]
增加了一个[设置scaleX](https://github.com/weidongjian/androidWheelView/commit/0654fc870bf4246609169467c5ec81f2ce1b7205)的方法，设置为1，折没有错位效果

**Comment by QiLiKing** [comment]
setScaleX没有重新设置paint，其实没效果的
