### ISSUE TITLE
无法设置控件的宽度

### ISSUE THREAD

**Issue by plplum** [weidongjian/androidWheelView#15]
固定宽度或者fill都不可以

**Comment by 23hp** [comment]
同问

**Comment by 23hp** [comment]
我改好了 可以宽度全屏

    int widthMeasureSpec;
    @Override
    protected void onMeasure(int widthMeasureSpec, int heightMeasureSpec) {
        this.widthMeasureSpec = widthMeasureSpec;
       ...
    }
   
    private void remeasure() {
        ...
        measuredWidth = MeasureSpec.getSize(widthMeasureSpec);
        //measuredWidth = maxTextWidth + paddingLeft + paddingRight;
        ...
    }

**Comment by weidongjian** [comment]
已修复，目前可以根据同步view的宽高
