### ISSUE TITLE
第二次设置setInitPosition（0）不管用

### ISSUE THREAD

**Issue by sunkeding** [weidongjian/androidWheelView#18]
有左右两个滚轮，右边数据是要随着左边数据发生变化，右边滚轮滚动一次之后，滚动左边滚轮，此时右边数据需要改变，把右边滚轮的初始位置设置为0；设置setInitPosition（0）不管用，请问该如何解决？

**Comment by weidongjian** [comment]
增加了设置当前item位置的方法，setCurrentPosition();
