### ISSUE TITLE
can't compile with java8 in android studio 2.2.2

### ISSUE THREAD

**Issue by Adam0407** [weidongjian/androidWheelView#19]
Error:Error converting bytecode to dex:
Cause: Dex cannot parse version 52 byte code.
This is caused by library dependencies that have been compiled using Java 8 or above.
If you are using the 'java' gradle plugin in a library submodule add 
targetCompatibility = '1.7'
sourceCompatibility = '1.7'
to that submodule's build.gradle file.

**Comment by weidongjian** [comment]
之前有强制使用java8，现在已移除
