### ISSUE TITLE
setCurrentPosition 方法里 position应该是大于等于0

### ISSUE THREAD

**Issue by ssj64260** [weidongjian/androidWheelView#23]
public void setCurrentPosition(int position) {
       //if (position >= 0 && position < items.size() && position != selectedItem) {
        if (position > 0 && position < items.size() && position != selectedItem) {
            initPosition = position;
            totalScrollY = 0;
            mOffset = 0;
            invalidate();
        }
    }

**Comment by SoyaLeaf** [comment]
+1

**Comment by weidongjian** [comment]
感谢提醒，已修复
