### ISSUE TITLE
setCurrentPosition(0) 还是有问题，会跳到数据的一半的位置

### ISSUE THREAD

**Issue by 287138531** [weidongjian/androidWheelView#28]
setCurrentPosition(0) 还是有问题，会跳到数据的一半的位置

**Comment by weidongjian** [comment]
我这边测试是正常的，请问你用项目的sample测试过吗？

**Comment by 287138531** [comment]
没跑过sample。我这里直接是在项目用，也确认是 0.12 版本

**Comment by weidongjian** [comment]
用sample试下，sample也是用0.12版本的

**Comment by DarkSherlock** [comment]
确实会调到数据的一半位置

**Comment by lindow2009** [comment]
我这边也遇到了，0.12版本，一样的问题

**Comment by anzhuojinjie** [comment]
setCurrentPosition(0) 还是有问题，会跳到数据的一半的位置，这个怎么解决呀 我也遇到了

**Comment by Lymmzy** [comment]
我看了一下，这个好像是由于selectedItem默认为0，而在setCurrentPosition()的时候，参数如果和selectedItem一致initPosition就不会改变了。所以出现了传0没有效果的情况。而加载完成后，由于initposition为-1，selectedItem默认变为中间数，这时候setCurrentPosition(0)就有效果了。
`public void setCurrentPosition(int position) {
        if (items == null || items.isEmpty()) {
            return;
        }
        int size = items.size();
        if (position >= 0 && position < size && position != selectedItem) {
            initPosition = position;
            totalScrollY = 0;
            mOffset = 0;
            invalidate();
        }
    }`

**Comment by weidongjian** [comment]
@anzhuojinjie 你是设置初始位置吗？调用`setCurrentPosition()`，设置初始位置要调用`setInitPosition()`的方法

**Comment by anzhuojinjie** [comment]
感谢您的回复。跟了一下源码我已经找到了，初始的时候需要调用
setInitPosition()，其他时候需要使用setCurrentPosition()，建议把这一点写在readme的使用文档中 @weidongjian

**Comment by weidongjian** [comment]
@anzhuojinjie 已经加到文档中了，谢谢反馈，最新项目太忙，回复晚了

**Comment by anzhuojinjie** [comment]
辛苦了 @weidongjian
