### ISSUE TITLE
中间的文字未垂直居中

### ISSUE THREAD

**Issue by Lesences** [weidongjian/androidWheelView#37]
如图，**LoopView 布局高度设置的为150dp**

![image](https://user-images.githubusercontent.com/10251423/28870557-4ab9ce78-77b3-11e7-979c-0ab90c0688f0.png)

此外，itemsVisibleCount也有问题，我这边是**设置的7，显示5个**

**Comment by huanting** [comment]
是因为文字draw的时候，传入的y值不对，应该传入的是baseLine位置；
设置itemsVisibleCount是包含了半圆 的最上面(+90°方向）和最下面(-90°方向)2个item

**Comment by orangegithub1** [comment]
@huanting 可以分享下具体实现吗？谢谢

**Comment by weidongjian** [comment]
已修复
https://github.com/weidongjian/androidWheelView/releases/tag/0.2.0
