### ISSUE TITLE
初始化设定setInitPosition(N),但未滑动则getSelectedItem()=0

### ISSUE THREAD

**Issue by 18616505009** [weidongjian/androidWheelView#50]
初始化loopView.setInitPosition(N)设置位置为任意数值N
在用户未滑动情况下,直接获取设定位置getSelectedItem()一直是0
滑动loopview后,getSelectedItem()才正常

**Comment by weidongjian** [comment]
你需要在viewmeasure之前，就调用setinitposition方法，就没有问题
可以在findviewbyid的返回的时候，就调用
