### ISSUE TITLE
设计建议，能不能不要按半圆柱面显示。

### ISSUE THREAD

**Issue by senlsy** [weidongjian/androidWheelView#51]
用height做作为直径，显示的是半个圆柱的面，现在很多扁平话UI都不需要这么大弧度，我直接修改了半径变量，显示效果错误。你应该是用itemheight * count/pi来计算半径，强制用measuredHeight 作为直径和为text total hight，太不灵活了。可以考虑下建议，添加个0-180的参数来设置弧度，所有item肯定都是要显示在屏幕上的，设置半径就可以很容易控制弧度，基本适合所有wheel的ui设计了，这才是灵活的设计。快实现吧，现在只能先换个控件了，

         radius = measuredHeight * 30;//直接让半径*30，效果错误
        halfCircumference = (int) (radius * Math.PI);
        // maxTextHeight = (int) (halfCircumference / (lineSpacingMultiplier * (itemsVisibleCount - 1)));

**Comment by proud2008** [comment]
@senlsy 你那的那个控件，地址发下

**Comment by yanghuaangel** [comment]
确实，能不能 有一个设置选项，可以让用户 设置 是否使用3D 显示，还是平铺

**Comment by weidongjian** [comment]
最新版本已支持
