### ISSUE TITLE
回调时间比较长

### ISSUE THREAD

**Issue by wss991** [weidongjian/androidWheelView#54]
当该控件位于popupwindow 或者dialog中，滑动之后，就点击确定，回调的index是上一次的，

**Comment by petma** [comment]
遇到了相同的问题

**Comment by weidongjian** [comment]
没有复现，是不是滚动还没有停止的时候，就点击的确定

**Comment by wss991** [comment]
是的，我现在不以回调为主，是在点击的时候去获取getSelect ，这样的话以当前滚动的实实位置为主了。
