### ISSUE TITLE
item String 值一样，选中事件回调index有误

### ISSUE THREAD

**Issue by NewbieFish** [weidongjian/androidWheelView#55]
控件设置的数据集值一样，eg，每个item 值  都是 “1”，onItemSelected事件 回调的 index 值 有误，都是0

**Comment by NewbieFish** [comment]
下载下来 集成  model  没有这个错 .

**Comment by weidongjian** [comment]
已修复 https://github.com/weidongjian/androidWheelView/releases/tag/0.2.0
