### ISSUE TITLE
最新版得sample。setCurrentPosition(0)还是无效啊

### ISSUE THREAD

**Issue by dianbaiyizhong** [weidongjian/androidWheelView#63]
setCurrentPosition(1)就可以。。。setCurrentPosition(0)不可以。。急求解决，老板

**Comment by ghost** [comment]
> setCurrentPosition(1)就可以。。。setCurrentPosition(0)不可以。。急求解决，老板

我也一样~~~~

**Comment by weidongjian** [comment]
已修复，我晚点重新出个版本

**Comment by dianbaiyizhong** [comment]
新发布的0.2.2好想依然没解决嘛，楼主么么

**Comment by weidongjian** [comment]
已经解决了，你直接运行项目看下，项目也是改成依赖0.2.2了 @huanghaoming

**Comment by dianbaiyizhong** [comment]
我测试了一下，最新版的。。。如果再重新设置了数据，setCurrentPosition 就无效了
楼主可以试试
 findViewById(R.id.button).setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                int number = (int) (Math.random() * 100) + 1;
                ArrayList<String> list = new ArrayList<>();
                for (int i = 0; i < number; i++) {
                    list.add("item gp" + number + i);
                }
                loopView.setItems(list);


                loopView.setCurrentPosition(0);
            }
        });

**Comment by weidongjian** [comment]
这边自测是正常的，两个button，第一个button重新设置数据，第二个button调用setCurrentPosition(0);
Button1:
int number = (int) (Math.random() * 100) + 1;
ArrayList list = new ArrayList<>();
for (int i = 0; i < number; i++) {
list.add("item gp" + number + i);
}
loopView.setItems(list);

Button2：
loopView.setCurrentPosition(0);


先点击button1，滑动滚轮，再点击button2会恢复到0的位置
