### ISSUE TITLE
我刚修复了LoopView中setCurrentPosition不触发OnItemSelectedListener的问题

### ISSUE THREAD

**Issue by Eugene-Zhou** [weidongjian/androidWheelView#72]
### 问题描述：
我在界面中有一个LoopView，实现了OnItemSelectedListener，使用了一个类变量来记录当前的滚动位置。
代码如下：

``` java
LoopView loopView = findViewById(R.id.xxxx);
int curSelectIndex;

OnItemSelectedListener selectListener = new OnItemSelectedListener() {
    @Override
    public void onItemSelected(int index) {
        curSelectedIndex = inex;
    }
};

loopView.setListener(selectListener);
```

用手指滑动，打印出来的curSelectedIndex都是对的。但是！另外一个地方使用代码调用loopView.setCurrentPosition(0);之后，再打印curSelectedIndex，却还是原来的值。意思就是说，setCurrentPosition(0)不会触发OnItemSelectedListener回调。

### 问题解决：
在LoopView.java的setCurrentPosition(int index)方法中invalidate()之前加入2行：
```java
remeasure();
handler.sendEmptyMessage(MessageHandler.WHAT_ITEM_SELECTED);
```
即可解决问题。

**Comment by weidongjian** [comment]
感谢反馈，已更新修复
